### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by botondsulyok** [BME-MIT-IET/iet-hf2021-we-have-todo-iet#4]
Technológia fókusz: Egységtesztek készítése + tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése

**Comment by botondsulyok** [comment]
ViewModel, Presenter, Interactor, DataSource tesztelése

**Comment by Beenty** [comment]
Ezt egy órán belül elkezdem csinálni.

**Comment by botondsulyok** [comment]
> Ezt egy órán belül elkezdem csinálni.

Elkezdted már? Mert most mergeljük a UI tesztet, és egy kicsit változott a viewmodel, mert kellett hozzá csinálni a teszt miatt egy absztrakt ősosztályt?

**Comment by Beenty** [comment]
A ViewModel tesztlefedettsége jelenleg (Class%, Method%, Line%) : 100%, 100%, 93%.
A Presenter tesztlefedettsége jelenleg (Class%, Method%, Line%) : 100%, 100%, 100%.
Most fogom csinálni az Interactor és a DataSource teszteléseket, holnapra szerintem be is fejezem :)
